#!/usr/bin/env python3
import sys
import itertools

MOD = 1000000007  # type: int


def solve(N: int, M: int, K: int):
    nm = N * M

    def get_pos(i,n,m):
        return i // m , i % m

    cost = 0
    for seq in itertools.combinations(range(nm),K):
        for i in range(len(seq)-1):
            x1,y1 = get_pos(seq[i],N,M)
            for j in range(i+1,len(seq)):
                x2,y2 = get_pos(seq[j],N,M)
                cost += (abs(x1-x2) + abs(y1-y2))

    print(cost)



# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, M, K)

if __name__ == '__main__':
    main()
